# This is a basic workflow to help you get started with Actions

name: Markdown to HTML with GitHub Style
            
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Job:
    runs-on: windows-latest
    steps:
      - name: Convert Markdown to HTML
        uses: natescherer/markdown-to-html-with-github-style-action@v1
        with:
          path: README.md,CHANGELOG.md,docs\doc1.md
          outputpath: out
